### ISSUE TITLE
Туториал в формате Markdown?

### ISSUE THREAD

**Issue by Steindvart** [zalexdev/pentutor#3]
Приветствую!

Делиться знаниями с миром – это очень благородная и значимая цель. Тогда почему бы не достигать её с помощью наиболее доступных и расширяемых средств (и возможно более безопасных, не каждый способен). В частности, перевести туториал в Markdown, который можно вполне себе успешно смотреть из того же GitHub'а.

**Comment by zalexdev** [comment]
Здравствуйте, данная работа была тестовой и не планируется её дальнейшая поддержка и обновление. Но в ближайшем будущем разделы можно будет посмотреть на Github pages

**Comment by Steindvart** [comment]
Хорошо, спасибо. Просто на будущее, очень было бы здорово видеть подобные образовательные материалы в максимально простом формате – текстовом. Markdown идеальный вариант, который способен интерпретироваться огромным количеством платформ ([вот хороший пример данного подхода](https://github.com/microsoft/Web-Dev-For-Beginners)).

К тому же, так удобнее всего будет вносить сообществу свой вклад. Если понадобится более расширенный функционал - проверочные тесты, моделирование ситуаций и тд., то тут уже следует задуматься над разработкой более обширной и глубокой платформы.
